# Generated by Django 3.1.4 on 2020-12-30 03:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.create_random_room_code, max_length=8, unique=True),
        ),
    ]
